export default [{
    title:'首页',
    key:'/'
},{
    title:'UI',
    key:'/admin/ui',
    children:[{
        title:'按钮',
        key:'/admin/ui/buttons',
    },{
        title:'弹框',
        key:'/admin/ui/modals',
    },{
        title:'Loading',
        key:'/admin/ui/loading',
    }]
},{
    title:'表单',
    key:'/admin/form',
    children:[{
        title:'登录',
        key:'/admin/form/login'
    },{
        title:'注册',
        key:'/admin/form/register'
    }]
}]